services:
  - type: web
    name: tictactoe-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: CLIENT_URL
        value: https://your-tictactoe-app.vercel.app